### ISSUE TITLE
Models API is not standard

### ISSUE THREAD

**Issue by tpoisot** [ibartomeus/traitmatch#4]
I think that (for homogeneity), https://github.com/ibartomeus/traitmatch/blob/master/R/models.R#L42 should have the same parameters as *e.g.* https://github.com/ibartomeus/traitmatch/blob/master/R/models.R#L22

That way, you can easily swap one model for another (or test multiple ones with the same set of parameters).

**Comment by ibartomeus** [comment]
But the neutral model has no pars. Would you recommend to include a "pars = NULL" parameter? I can do that but I am not sure if this can be confusing for the user, as NULL is the only value it can get.

**Comment by tpoisot** [comment]
I agree, **but**:

Imagine that someone wants to write another model to use with the package. It then becomes important that all models accept the same type of parameters. So I would definitely encourage you to do it. One possible way is (note the second line):

~~~ R
neutral_model = function(pars=NULL, Tlevel1, Tlevel2, mean_Tlevel1, sd_Tlevel1) {
	if (!is.null(pars)) warning("The neutral_model function does not use the content of the argument pars")
	# Compute the conditional
	pLM = 1
	# Compute the marginal
	pM = dnorm(x=Tlevel1, mean = mean_Tlevel1, sd = sd_Tlevel1)
	#  Integrate the denominator
	pL = 1
	# Compute the posterior probability
	pML = pLM*pM/pL
	pML[pML<=0] = .Machine$double.xmin # Control to avoid computing issues
	return(-sum(log(pML)))		
}
~~~

Another point is that currently, none of the other arguments have default values, which will cause nasty crashes. One thing that having the same API for all models allows is to write a `check_model_input` function that would ensure that the arguments are defined, of the right type, etc etc. Then the first line of *any* model function is a call to `check_model_input`, which raises appropriate warnings if needed.

**Comment by ibartomeus** [comment]
I see the benefits of `check_model_input` but this will have to wait.
