### ISSUE TITLE
packages are not correctly imported

### ISSUE THREAD

**Issue by tpoisot** [ibartomeus/traitmatch#6]
https://github.com/ibartomeus/traitmatch/blob/master/R/plot_pred.R#L30

The "right" (according to R CMD CHECK --as-cran) way to import packages is to list them as `Imports` in the `DESCRIPTION` (see https://github.com/PoisotLab/betalink/blob/master/DESCRIPTION for an example), then call the functions using `package::function` in the code.

**Comment by ibartomeus** [comment]
Done!

**Comment by tpoisot** [comment]
:+1: 

PS: If you use # and the number of the issue (here #6) in the commit message, it will show up in the discussion attached. You can also write `Closes #6`, which will automatically close the issue (https://help.github.com/articles/closing-issues-via-commit-messages/).
